force-app/main/default/objects/Platform_Event_Main__e/Platform_Event_Main__e.object-meta.xml
<CustomObject>
    <label>Platform Event Main</label>
    <pluralLabel>Platform Events Main</pluralLabel>
</CustomObject>

force-app/main/default/objects/Platform_Event_Main__e/fields/Is_Test__c.field-meta.xml
<CustomField>
    <fullName>Is_Test__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Test</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PlatformEventPublisher.cls
public without sharing class PlatformEventPublisher {
    public static void publishMainEvent(String message, Boolean isTest) {
        Platform_Event_Main__e eventObj = new Platform_Event_Main__e();
        eventObj.Is_Test__c = isTest;
        eventObj.Status_Message__c = message;
        
        EventBus.publish(eventObj);
    }

    @AuraEnabled(cacheable=true)
    public static String getSessionId() {
        return UserInfo.getSessionId();
    }
}